✨ 애플로그인을 파이어베이스 연동으로 변경했습니다 & 💄LoginViewController의 UI를 구현했습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #12
Opened 2022-11-01 13:03 UTC by Kim-Yeon-ho

## 배경
- 앱의 사용자 데이터 관리를 파이어베이스를 통해 하기때문에 애플 로그인으로 하는 사용자도 파이어베이스로 데이터로 연동을 하여 관리를 할 수 있도록 변경했습니다.

- 이메일 로그인도 다시 추가하다보니 결국 UI를 건들게 되었습니다...죄송합니다..작업량이 더 늘기 전에 올립니다.

- 앱의 주 폰트 추가 및 메인 컬러 핑크가 추가되어있습니다.

## 작업 내용 (Content)
- 파이어베이스 연동을 통한 애플로그인
- LoginViewController의 UI작업
- CustomColor 및 Font 추가

현재 이메일을 통한 로그인을 할때 파이어베이스에 이메일 값과 패스워드를 저장하는 코드의 과정에서 문제가 있는지 "Failed to create user"의 오류가 뜨는 상황입니다. 

<p align="left">
  <img width="900" alt="스크린샷1" src="https://user-images.githubusercontent.com/81131715/199237323-9892053d-ee6b-451f-994f-f2e6c2620356.png">
</p>
<p align="left">
<img width="900" alt="스크린샷1" src="https://user-images.githubusercontent.com/81131715/199237724-5a9fc4f6-b70a-4916-85c6-d5f977e3672c.png">
</p>

## 스크린샷

<p align="left">
  <img width="300" alt="스크린샷1" src="https://user-images.githubusercontent.com/81131715/199236526-489e0edb-f340-4918-8dc5-589a5d1867f4.gif">
</p>

## 테스트방법
- PR리뷰어가 변경사항을 확인할 수 있는 방법을 서술합니다.
  - 그대로 실행하셔서 애플 로그인을 해보시고 프로필에 가셔서 signOut버튼을 눌러보시면 회원탈퇴도 됩니다.

## PR & Issues
- #7

## 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

2022-11-01 15:40 UTC, Rookie0031 requested changes
## 고생하셨슴당

시뮬레이터로 잘되는거 체크했습니다 굿굿

근데 제가 테스트할 때는 failed to create user오류는 떳지만, 그렇게 만든 계정으로 다시 로그인하면 접속은 되더라구요? 저 구문에서 do try catch 형식으로 에러를 잡으면 저 문자를 프린트하는데, 어떤 에러를 잡아서 저게 나는지 좀 살펴보면 좋을 것 같습니다. 로그인은 되는데 다른 에러를 catch해서 저게 프린트가 된다던지 하는.. 뭐 그런거로 생각되네요
<img width="600" alt="image" src="https://user-images.githubusercontent.com/103009135/199274219-c2a647e6-cbd8-4123-92b2-5a3f398353e0.png">

2022-11-01 15:40 UTC, Rookie0031 commented on Flicker/Global/Supports/AppDelegate.swift
> +            print("로그인되어있음", user.uid, user.email ?? "-")
p5
요기엔 추후에 어떤 코드가 들어올 예정인가요??

2022-11-01 15:40 UTC, Rookie0031 commented on Flicker/Screens/Login/LoginViewController.swift
>          $0.addTarget(self, action: #selector(handleAuthorizationAppleIDButtonPress), for: .touchUpInside)
p3
애플 로그인을 흰색으로 한 이유가 있나요?? 전부 밝은 느낌이라 흰색도 나쁘지않긴하네요

2022-11-01 15:40 UTC, Rookie0031 commented on Flicker/Screens/Login/LoginViewController.swift
> +        $0.font = UIFont(name: "TsukimiRounded-Bold", size: 30)
p2
이전 프로젝트에서 했던 대로 일부 텍스트를 제외하면 폰트사이즈를 최대한 비슷한 거로 동적 지정으로 하면 좋을 거 같습니다!

![image](https://user-images.githubusercontent.com/103009135/199270545-bf4c36e8-11f7-41e5-a73a-d9594b6c0e61.png)

2022-11-01 15:40 UTC, Rookie0031 commented on Flicker/Screens/Login/LoginViewController.swift
> +    private func sha256(_ input: String) -> String {
p4
이 함수의 역할이 뭔가요?? + nonce가 무엇인가요??

2022-11-01 15:53 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/LoginViewController.swift
>          $0.addTarget(self, action: #selector(handleAuthorizationAppleIDButtonPress), for: .touchUpInside)
흰색은 저번에 피파옆에서 작업할 때 물어보고 흰색으로 진행했어서 우선 그대로 뒀습니다!
언제든 바꿀 수 있으니 얘기 해봅시다!!

2022-11-01 15:54 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/LoginViewController.swift
> +        $0.font = UIFont(name: "TsukimiRounded-Bold", size: 30)
이게 폰트를 커스텀으로 적용하면 폰트크기를 저렇게 지정할 수 없게 되더라구요..피파에게 오전에 전달해 놓은 상황입니다ㅠㅠ

2022-11-01 15:55 UTC, Kim-Yeon-ho commented on Flicker/Global/Supports/AppDelegate.swift
> +            print("로그인되어있음", user.uid, user.email ?? "-")
이 코드는 제가 지웠었는데 변경하도록 하겠습니다!

2022-11-01 15:55 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/LoginViewController.swift
> +        $0.textColor = .black
반영하도록 하겠습니다!

2022-11-01 15:58 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/LoginViewController.swift
> +    private func sha256(_ input: String) -> String {
nonce는 임의의 문자열을 의미합니다! nonce는 한 번 사용된 숫자의 약자를 말합니다.
sha256함수는nonce값을 해제하기 불가능하게 하는 함수라고 합니다.. 파베 공식문서에 기본적으로 제공되어서 쓱싹 가져다 썼습니다

2022-11-01 23:23 UTC, Rookie0031 approved these changes

2022-11-02 00:39 UTC, coby5502 approved these changes

2022-11-02 00:45 UTC, merged