✨ 회원가입시 닉네임의 길이를 8글자로 제한하는 기능을 추가했습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #163
Opened 2022-11-28 19:58 UTC by Kim-Yeon-ho

## 🌁 배경
- 프로필 세팅뷰에서 일정 길이 이상으로 닉네임의 String값이 들어가면 UI적으로 문제가 생겨 자체적으로 닉네임의 길이를 8글자로 제한하기로 했습니다.

## 👩‍💻 작업 내용 (Content)
- 닉네임을 적는 텍스트 필드의 길이가 8글자 이상이 될 경우 더 이상 입력을 할 수 없도록 했습니다.
- 추가적으로 모든 입력이 불가해, 지우기 조차 불가하여 백스페이스입력은 가능하도록 코드를 추가했습니다.
- UI적으로 현재 몇글자를 입력했고 몇글자까지 입력할 수 있는지 보여줘 사용자가 알 수 있도록 했습니다.

String은 호출되는 함수의 Parameter로 들어오는 값이며, 사용자가 입력을 시도한 값이 실제 입력이 되는지 여부와 관계없이 계속 들어오게 됩니다. 이때 들어오는 값중 BackSpace값을 판단하고 인코딩하여 UInt32형태로 변환합니다.
BackSpace의 UInt32값은 -92이며,이 조건을 만족하는 경우는 입력을 가능하도록 하여 BackSpace입력은 가능하도록 했습니다.
![스크린샷 2022-11-29 오전 4 51 16](https://user-images.githubusercontent.com/81131715/204368062-3c992e4e-c047-4d6e-9550-16cb9705718d.png)

## 📱 스크린샷
- 화면 전환이나 인터렉션이 있는 경우엔 GIF, 정적인 화면이라면 스크린샷을 이용합니다.

https://user-images.githubusercontent.com/81131715/204367485-bbfaebe4-e251-4f66-a297-bd6796199af6.mp4

## ✅ 테스트방법
회원가입 시 프로필입력 화면에서 닉네임을 입력해보시면 됩니다!

## 📣 PR & Issues
- closed #160 

## 📬 참고문서, 레퍼런스
- https://kasroid.github.io/posts/ios/20200914-uitextfield-limits-number-of-text-detecting-backspace-event/#backspace-event-%EA%B0%90%EC%A7%80%ED%95%98%EA%B8%B0

2022-11-28 23:31 UTC, Rookie0031 requested changes
## 고생하셧슴다!!

제 생각엔 SignupView와 LoginProfileView 맨위 상단에 있는 Divider는 이제 빼는게 좋지않을까요?? 네비바가 없는 형태라서 디바이더가 필요없을 거 같습니다! 

https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/blob/7e1901ff0f77fcc41529947f7b4f71cb8d224993/Flicker/Screens/SignUp/LoginProfileViewController.swift#L123-L125

2022-11-29 00:12 UTC, Kim-Yeon-ho commented
> ## 고생하셧슴다!!
> 제 생각엔 SignupView와 LoginProfileView 맨위 상단에 있는 Divider는 이제 빼는게 좋지않을까요?? 네비바가 없는 형태라서 디바이더가 필요없을 거 같습니다!
> 
> https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/blob/7e1901ff0f77fcc41529947f7b4f71cb8d224993/Flicker/Screens/SignUp/LoginProfileViewController.swift#L123-L125

우리 디발자한테 물어보고 없에는 것이 낫다고 의견을 들어서 디바이더를 지우는 것으로 하겠습니다!

2022-11-29 00:21 UTC, coby5502 approved these changes

2022-11-29 00:25 UTC, Rookie0031 approved these changes

2022-11-29 00:25 UTC, merged