💄 MainView UI 구현
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #17
Opened 2022-11-03 05:48 UTC by coby5502

## 배경
- 메인 화면을 구현하였습니다.

## 작업 내용 (Content)
- [x] 지역 태그 리스트 ColletionView로 구현
- [x] 지역 태그 Cell UI
- [x] 작가 썸네일 리스트 ColletionView로 구현
- [x] 작가 썸네일 Cell UI

- 데이터를 불러오는 코드 없이, 간단한 UI만 구성하였습니다.
- 지역 태그를 선택했을 때, 어떤 태그를 클릭했는지 정도까지만 코드를 구현하였습니다.

## 스크린샷

<p align="left">
  <img width="200" alt="스크린샷1" src="https://user-images.githubusercontent.com/57849386/199654600-e508fa88-73d3-4992-b2e8-cacf207aed30.png">
</p>

## 테스트방법
- 해당 브랜치에서 빌드하시면 됩니다. 

## 추가 전달사항
- 작가 썸네일에서, 사진 배경에 따라, 글자 스타일이 변경되거나 다른 디자인을 해야할 것 같습니다.
- 배경이 밝으면, 기존의 하얀색 폰트가 잘 보이지 않습니다.
- 마찬가지로, 작가 썸네일 안의, 작가 프로필이미지도 인스타그램처럼 테두리라도 넣을까 싶습니다.

## PR & Issues
- #16

## 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

2022-11-03 05:52 UTC, coby5502 commented on Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
> +        }
픠그마를 참고하였을 때, 작가 소개는 최대 두 줄인 것으로 보았습니다.
따라서 작가 소개 라벨의 너비를 220으로 제한하였으며,
두 줄이 넘어갈 시에는 텍스트가 생략되고 ...으로 끝나게 됩니다.

2022-11-03 05:52 UTC, coby5502 commented on Flicker/Screens/Main/Cell/RegionCollectionViewCell.swift
> +    }
지역 태그가 선택되면, 검정으로 스타일이 변하고, 이미 선택된 태그는 disabled 됩니다.

2022-11-03 08:01 UTC, Rookie0031 requested changes
## 고생하셨슴다!

슈퍼개발자 킹도영 뚝딱 만드셧군요. 
작가 썸네일에서 UI 수정이 좀 필요해보이긴합니다. 일단은 제가 최대한 노력해서 괜찮은게 있는지 찾아보져.

ArtistTappedView는 일단은 제 파트인데 이 부분에 데이터 연동 작업이 들어가면 naviagtion할 때 데이터전달도 구현되어야될 것 같고 그러면 ArtistTappedView까지 한명이서 작업하는게 더 편할 거 같네요 그 부분은 추후 이야기해보면 될 거 같습니다.
 굿굿

2022-11-03 13:15 UTC, Kim-Yeon-ho approved these changes
고생하셨슴둥!

2022-11-03 13:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
> +        }
p5
저희 나중에 각 컴포넌트들의 크기를 고정값이 아닌 기기별 width 와 height에 맞춰서 바꾸면 어떨까요?

2022-11-03 15:59 UTC, PecanPiePOS approved these changes
고생하셨습니다 코비프로

2022-11-03 15:59 UTC, PecanPiePOS commented on Flicker/Screens/Main/MainViewController.swift
> +    }
p5
이넘 잘 쓰는 남자 너무 멋있네요
enum 구조에 대해 한번 더 맛보고 갑니다~

2022-11-03 15:59 UTC, PecanPiePOS commented on Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
> +    private let reigionList = ["전체", "서울", "부산", "포항", "동해", "삼척", "강릉", "춘천", "속초"]
p2
저는 사실 텍스트 어레이 여도 괜찮다고 봅니다! 만약 케이스가 많다면...

2022-11-03 15:59 UTC, PecanPiePOS commented on Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
> +    }
혹시 이게 어떤 기능을 하는지 간략하게 설명해주실 수 있으실까요? (핑프핑프)

2022-11-04 00:24 UTC, Rookie0031 approved these changes

2022-11-04 00:25 UTC, coby5502 commented on Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
> +    }
지역 태그 리스트뷰를 따로 뺐잖아요?
여기서 선택한 지역 태그를, MainController에서 값을 가져오려고 연결하는 코드입니다.

2022-11-04 00:25 UTC, coby5502 commented on Flicker/Screens/Main/UIComponent/RegionListHorizontalView.swift
> +    private let reigionList = ["전체", "서울", "부산", "포항", "동해", "삼척", "강릉", "춘천", "속초"]
저희 아직 지역을 어떻게 할지 얘기된 바가 없는 것 같아서, 간단한 UI구현을 위해 배열로 일단 짰습니다.
추후에는 앱 전체에서 쓸 이넘을 만드는 것이 좋을 겁니다.

2022-11-04 00:26 UTC, coby5502 commented on Flicker/Screens/Main/Cell/ArtistThumnailCollectionViewCell.swift
> +        }
네넵 다음에 반영하겠습니다.

2022-11-04 00:26 UTC, merged