:lipstick: 로그인 플로우에 맞는 디자인을 구현했습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #18
Opened 2022-11-03 14:05 UTC by Kim-Yeon-ho

## 배경
- 로그인에서 회원가입 시 입력하는 플로우에 따라 UI를 구현했습니다.
- 애플로그인시에도 닉네임과 작가여부를 판단하는 뷰로 들어가도록 했습니다.

## 작업 내용 (Content)
- 앱에 처음 들어왔을 때 사용자가 로그인 및 초기설정을 하는 뷰를 만들었습니다.

- 필요한 값을 입력하지 않았을 경우 화면이 넘어가지않도록 구현하였습니다.

- 이메일 로그인에서의 오류는 아직 해결하지 않았습니다.

- 이미지 클릭 시 프로필 사진 구현은 코비가 구현하신 코드를 잘 활용할 예정입니다.

- 닉네임을 적는 텍스트 필드의 디자인은 사실 피그마와 다른데 우선 저렇게 구현했습니다..
## 스크린샷
- 좌측은 회원가입 플로우 이며, 우측은 둘러보기 시 입니다.
<p align="left">
  <img width="300" alt="스크린샷1" src="https://user-images.githubusercontent.com/81131715/199738572-36542001-8afa-49cc-af1a-61cdc5725e30.gif">
  <img width="300" alt="스크린샷2" src="https://user-images.githubusercontent.com/81131715/199738891-e5d73e06-0c0c-4c55-b17b-968b0495809a.gif">
</p>

## 테스트방법
- 제 브랜치에 들어가셔서 바로 실행해보시면 로그인 화면이라 바로 뜨실껍니다앗!

## PR & Issues
- closed #13 

## 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

2022-11-03 14:21 UTC, Kim-Yeon-ho commented on Flicker/Screens/SignUp/LoginProfileViewController.swift
> +    private func labelTemplate(labelText: String, textColor: UIColor ,fontStyle: UIFont.TextStyle, fontWeight: UIFont.Weight) -> UILabel {
라벨에 텍스트값만 쓰는 컴포넌트가 많아서 함수로 만들어서 사용했습니다.

2022-11-03 14:22 UTC, Kim-Yeon-ho commented
화면이 탭바뷰컨으로 갈때 최상단에 생기는 네비게이션바를 지우고 싶은데 베이스뷰컨에서 어떻게 건들여야 할지..모르겠습니다.

2022-11-03 15:27 UTC, Rookie0031 requested changes
## 고생하셧슴다!!

UI좀 다듬고 데이터연동 들어가면 되겟네여 버그사항들은 같이 찾아봅시다. 굿굿

2022-11-03 15:27 UTC, Rookie0031 commented on Flicker/Global/Extensions/UIColor+Extension.swift
> +        return UIColor(hex: "373333")
p1
컬러를 추가로 넣을 때 textMainBlack 부분에서 괄호 마무리가 안되서 빌드 에러가 나고 있슴당. 추가해서 없애주세용

2022-11-03 15:27 UTC, Rookie0031 commented on Flicker/Screens/Login/LoginViewController.swift
>          loginDivider1.snp.makeConstraints {
p2
변수명에 숫자를 직접 넣지 않는게 국룰이라고 하더라구요??(by Young) Dividerfirst, second.. 이런식으로 바꾸는걸 추천드립니다!

2022-11-03 15:27 UTC, Rookie0031 commented on Flicker/Screens/SignUp/LoginProfileViewController.swift
> +    private func labelTemplate(labelText: String, textColor: UIColor ,fontStyle: UIFont.TextStyle, fontWeight: UIFont.Weight) -> UILabel {
LGTM

2022-11-03 15:27 UTC, Rookie0031 commented on Flicker/Screens/SignUp/LoginProfileViewController.swift
> +    private lazy var profileLabel1 = labelTemplate(labelText: "자신을 보여줄 수 있는 간단한 프로필 사진을 보여주세요!", textColor: .textSubBlack, fontStyle: .caption1, fontWeight: .medium)
p2
마찬가지 이유로 숫자를 first같은거로!

2022-11-03 15:27 UTC, Rookie0031 commented on Flicker/Screens/SignUp/LoginProfileViewController.swift
> +    private lazy var afterjoinLabel = labelTemplate(labelText: "가입 후 마이프로필에서 작가등록을 하실 수 있어요!", textColor: .textSubBlack, fontStyle: .caption1, fontWeight: .medium)
p3
카멜케이스로 하면 afterJoinLabel이 되어야할 거 같은데 (j가 대문자!) 일부러 join까지 소문자로 한건가요??

2022-11-03 15:41 UTC, PecanPiePOS approved these changes
첫 단추 끼우느라 고생했습니다 하뒤!

2022-11-03 15:41 UTC, PecanPiePOS commented on Flicker/Screens/Login/LoginViewController.swift
> +        lookAroundButton.addTarget(self, action: #selector(didTapLookAroundButton), for: .touchUpInside)
p5
button action 에 관한건 render() 대신 따로 action 관련된 메서드로 빼서 넣는건 어떻게 생각하시나요? (제안)

2022-11-03 15:41 UTC, PecanPiePOS commented on Flicker/Screens/Login/LoginViewController.swift
> +    //TODO: 둘러보기 클릭하면 일단 메인 화면으로 가도록 설정은 해놨는데, 어떤 값을 줘서 입력을 하려할때, 혹은 기능을 쓰려할때 로그인이 필요하다고 뜨도록 해야 할 것 같습니다.
p5
멋집니당

2022-11-03 15:41 UTC, PecanPiePOS commented on Flicker/Screens/SignUp/LoginProfileViewController.swift
> +    private func labelTemplate(labelText: String, textColor: UIColor ,fontStyle: UIFont.TextStyle, fontWeight: UIFont.Weight) -> UILabel {
멋져욧

2022-11-03 15:41 UTC, PecanPiePOS commented on Flicker/Screens/SignUp/LoginProfileViewController.swift
> +        signUpButton.addTarget(self, action: #selector(didTapSignUpButton), for: .touchUpInside)
p5
button action 에 관한건 render() 대신 따로 action 관련된 메서드로 빼서 넣는건 어떻게 생각하시나요? (제안) 22

2022-11-03 15:41 UTC, PecanPiePOS commented on Flicker/Screens/SignUp/SignUpViewController.swift
> +class SignUpViewController: BaseViewController {
p4
final 을 빼신 이유를 알 수 있을까요??

2022-11-03 15:43 UTC, PecanPiePOS commented
화면이 탭바뷰컨으로 갈때 최상단에 생기는 네비게이션바를 지우고 싶은데 베이스뷰컨에서 어떻게 건들여야 할지..모르겠습니다.
에 대한 답을 제가 보고 가르쳐 드리겠습니다.

2022-11-03 15:47 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/LoginViewController.swift
> +        lookAroundButton.addTarget(self, action: #selector(didTapLookAroundButton), for: .touchUpInside)
내일 한번 같이 이야기 해보죠!! 저도 좋은 것 같습니다!

2022-11-04 00:23 UTC, Rookie0031 approved these changes

2022-11-04 00:30 UTC, coby5502 approved these changes
뿡

2022-11-04 00:30 UTC, merged