💄 메세지 관련 화면과 기능 구현
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #31
Opened 2022-11-08 01:17 UTC by coby5502

## 배경
- 코비톡에서 메시지 기능을 구현하였습니다.
- 코드를 가져와서 저희 앱에 맞게 수정하였습니다.

## 작업 내용 (Content)
- 메세지탭 클릭시, 채팅방 목록 보기
- 채팅방 내에서, 채팅 기능
- 유저, 최근 메세지, 메세지 모델 추가
- 파이어베이스 채팅 통신 코드 추가

## 스크린샷
- 화면 전환이나 인터렉션이 있는 경우엔 GIF, 정적인 화면이라면 스크린샷을 이용합니다.

<p align="left">
  <img width="200" alt="스크린샷1" src="사진URL">
  <img width="200" alt="스크린샷2" src="사진URL">
  <img width="200" alt="스크린샷3" src="사진URL">
</p>

## 테스트방법
- PR리뷰어가 변경사항을 확인할 수 있는 방법을 서술합니다.

## PR & Issues
- 현재 작성 중인 Pull Request와 관련된 PR과 Issues가 있다면 나열합니다.

## 참고문서, 레퍼런스
- 작업을 하면서 참고한 문서 및 레퍼런스를 작성합니다.

2022-11-08 07:17 UTC, coby5502 commented on Flicker/Global/UIComponent/PaddingLabel.swift
> +@IBDesignable class PaddingLabel: UILabel {
[fdeb7cd](https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/pull/31/commits/fdeb7cdd45a2b66a1855903a49eba3f08d37d890)
참고하면서 가져온 불필요한 코드로 보여, 삭제하였습니다!

2022-11-08 09:09 UTC, Rookie0031 requested changes
## 고생하셨슴다!!

슈퍼개발자 킹도영... 보면 볼수록 잘하는 것 같슴다. 리뷰에 질문을 좀 남겨봤습니다

2022-11-08 09:09 UTC, Rookie0031 commented on Flicker/Screens/Chat/ChatViewController.swift
> +        if chatMessages.contains(where: { rm in
p3
contains 구조를 이렇게 바꾸면 더 직관적이고 간결해보일 수 있을 것 같습니다
`
        if chatMessages.contains(where: { $0.id == docId }) {
            return
        }
`

근데 이 부분 코드에서 궁금한점이 있습니다. docId랑 같은 id를 가지는 메시지가 있으면 추가하라는 코드같은데 왜 if 문 뒤에 return을 쓰고 if문을 빠져나간 뒤에 chatMessages.append(chatMessage) 를 하나요??

2022-11-08 10:23 UTC, coby5502 commented on Flicker/Global/Utils/FirebaseManager.swift
> +        let document = firestore.collection("messages")
네 그렇습니다! 파베에서는 데이터를 저장하면 컬렉션이 자동으로 추가됩니다.

2022-11-08 10:26 UTC, coby5502 commented on Flicker/Screens/Chat/ChatViewController.swift
> +            getChatUserProfileImage()
저도 그렇게하고 싶은데, 코드가 안 먹더라구요.
이거로 삽질을 계속했는데, 결국 명쾌한 코드를 못 찾았습니다.
이미지 처리 관련해서 함께 공부해봅시다.
몰라서 그랬어요!

2022-11-08 10:28 UTC, coby5502 commented on Flicker/Screens/Channels/ChannelsViewController.swift
> +        $0.separatorInset = UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
Inset을 0으로 안주면, 테이블뷰 구분선의 여백이 왼쪽과 오른쪽이 다릅니다!

  <img width="200" alt="스크린샷1" src="https://user-images.githubusercontent.com/57849386/200540971-def6a632-899d-4026-bd44-43ccb50a296a.png">

이런식으로 됩니다! 기본값이 이렇거든요.

2022-11-08 10:36 UTC, coby5502 commented on Flicker/Screens/Chat/ChatViewController.swift
> +        if chatMessages.contains(where: { rm in
[080412f](https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/pull/31/commits/080412f4a0d8f48d3bc565b14c54e9787bbf3c57)

덕분에 코드 예쁘게 고쳤습니다.
FirebaseListener가 새롭게 변경된 데이터가 있으면, 테이블뷰에 반영하는 코드입니다.
그래서 기존 Id 값과 겹치면, 밑에 코드가 실행이 되지 않습니다.

2022-11-08 10:36 UTC, coby5502 commented on Flicker/Global/Utils/FirebaseManager.swift
> +        let ref = Storage.storage().reference(forURL: imageUrl)
[080412f](https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/pull/31/commits/080412f4a0d8f48d3bc565b14c54e9787bbf3c57)

꼼꼼하시네요. 수정했어요.

2022-11-08 10:46 UTC, coby5502 commented
> 직접 테스트를 해보고 싶은데 어떻게 하면 기능을 테스트 할 수 있나요?

코비톡 코드 그대로입니다. 그래서 한 번 테스트 해보도록 한거구요.
회원가입과 다른 화면들에서 서버가 아직 안 붙지 않았습니까?

원래는 다른 화면 작업 후에, 쓰윽 얹으려고 했지만
개발이 지연된 상태라서, 오히려 코드 참고하시라고, 미리 PR 올렸습니다.

추후에, 다른 화면과 유기적으로 잘 기능하는지 추가 테스트 후에, 다시 PR 올리겠습니다.

2022-11-08 11:54 UTC, Rookie0031 approved these changes

2022-11-10 05:23 UTC, PecanPiePOS approved these changes
전 코비 당신을 믿어요. 노션에 정리해둔 것 읽고 한번 더 이해해보도록 하겠습니닷

2022-11-10 05:23 UTC, PecanPiePOS commented on Flicker/Global/UIComponent/PaddingLabel.swift
> +}
p5
메세지 UILabel 이네요 이미 검증된 것이니 나중에 잘 배워가겠습니다.

2022-11-10 05:23 UTC, PecanPiePOS commented on Flicker/Global/Utils/FirebaseManager.swift
> +    }
p5
사진 용량 관련 공부해보겠습니다.

2022-11-10 05:24 UTC, merged