✨ 작가 등록 UI 및 기능 구현 [2]
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #36
Opened 2022-11-09 09:54 UTC by PecanPiePOS

## 🌁 배경
일단 조금 지체돼서 사과드립니다.
작가로 등록하는 프로세스의 기본 페이지는 다 구현을 했고, 공수 시간상 등록 시에 올린 데이터들로 꾸린 미리보기 뷰는 제외했습니다. 파이어베이스로의 post 기능을 위해선 데이터 모델들을 꾸려야 해 하나의 mainVC 로 데이터를 모으는 작업이 진행됐습니다.

## 👩‍💻 작업 내용 (Content)
- [x] 로고 등록
- [x] 등록 첫 페이지 VC
- [x] 실질적인 기능을 하는 5개의 VC 를 담을 수 있는 main VC 
- [x] 지역 설정 VC 📍(전 PR 에선 여기까지)
- [x] 장비 정보 VC
- [x] 자기 소개 VC
- [x] 포트폴리오(사진등록) VC
- [x] 등록 완료 VC

다른 분들도 마찬가지지만 새롭게 접한 기능들을 구현을 했고 그로 인해 하나하나의 코드에 대한 설명이 부족하거나 없을 수 있습니다.

**커스텀 델리게이트 사용** -> 생각보다 그렇게 어렵지 않았고 strict 하지 않게 Data 를 주고 받을 수 있어 편했습니다.

**장비 정보 VC** -> textField 가 2개가 위아래 종으로 배치되어 있어 NotificationCenter 를 통한 view 의 layout 변경을 진행했고, 키보드에 대한 자잘한 기능들을 모두 추가했습니다.
**자기 소개 VC** -> textView 가 크게 있어 이것 또한 layout 변경과 키보드 관련된 기능을 추가 했습니다.
**포트폴리오 VC** -> 최소 지원 버전이 13.0 에서 14.0 으로 올리게 된 가장 큰 이유로, 사진을 여러 개를 골라야 하는데 써드파티 라이브러리를 쓰자니 앱이 무거워지고 개발 공부에 도움이 되지 않을 것 같아, PHPickerViewController (iOS 14.0+) 를 사용하여 사진을 받아왔습니다. + 추가적으로 모든 데이터가 입력이 됐는지 안됐는지를 체크하여 AlertAction 을 넣었습니다.

** 모든 뷰는 iphone 13 mini, iphone 14 Pro, iphone 14 Pro Max 에서 모두 잘 되는지 확인했습니다.
.

## 📱 스크린샷

"popToRootVC!!"
  <img width="250" alt="gif" src="https://user-images.githubusercontent.com/89404664/200797352-0b6396df-cd74-415c-a9d0-d4e1d6e53826.gif">

<p align="left">
  <img width="250" alt="" src="https://user-images.githubusercontent.com/89404664/200798270-479fc243-7595-49ba-a548-01173aecbc27.png">
  <img width="250" alt="" src="https://user-images.githubusercontent.com/89404664/200798284-d4b287f6-ec1e-416e-af5a-c6762c284677.png">
</p>
데이터를 받기 위한 노오력

## ✅ 테스트방법
SceneDelegate.swift 에서 ArtistRegisterViewController❌ 가 아닌, RegisterWelcomeViewController 를 rootVC 로 받아 진행하면 바로 테스트 가능합니다.

## 📣 PR & Issues
#8 

## 📬 참고문서, 레퍼런스

### 😁 깃모지 (PR을 올릴 땐 지우고 올려주세요.)
 🎨 코드 구조/형태 개선 (리소스 이동, 파일 추가 및 삭제 포함)
⚡ 성능개선 (정량적으로 측정가능한 성능개선만 사용)
🐛 버그수정
🚑 긴급 수정
✨ 새 기능
📝 문서 추가/ 작성
💄 UI 관련 코드 수정

2022-11-09 09:57 UTC, Kim-Yeon-ho commented
깃모지 지워주세요ㅎ @PecanPiePOS

2022-11-09 10:15 UTC, Kim-Yeon-ho reviewed
@PecanPiePOS Comment 확인해주세요!

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
> +    private let mainTitleLabel = UILabel().then {
p5
요런거 LabelExtension쓰면 편합니다

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
> +        view.addSubview(mainTitleLabel)
p3
view.addSubviews를 안 쓰시는 이유가 있을까요??
코드의 통일성을 위해서 쓰시는 것이 좋을 것 같습니다!

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +extension ArtistRegisterViewController: RegisterRegionDelegate, RegisterGearsDelegate, RegisterTextInfoDelegate, RegisterPortfolioDelegate {
p5
delegate 장인.. 보고 배우겠슴다..

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +    static let mainTitleLabel = UILabel().then {
p5
LabelExtension 한번?

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
>      private let subTitleLabel = UILabel().then {
p5
LabelExtension 두번?

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +        view.addSubviews(RegisterGearsViewController.mainTitleLabel, subTitleLabel, bodyTitleLabel, cameraBodySectionLabel, cameraBodyExampleSectionLabel, cameraBodyTextField, cameraLensSectionLabel,
p3
addSubview 와 addSubviews가 왔다리 갔다리 시네요 통일해주세요

2022-11-09 10:15 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +            self.delegate?.cameraBodySelected(cameraBody: textField.text ?? "카메라 바디")
p5
self.delegate라고 하면 어떤 걸 의미하는건가요?? 델리장인피파?

2022-11-09 10:17 UTC, Kim-Yeon-ho commented
# LGTM
피파 보면서 uikit 꽤 많이 배웁니다.🫡

2022-11-09 10:42 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
> +        view.addSubview(mainTitleLabel)
아 ㅎ 전의 안좋은 legacy 가 여기에 복붙이 됐네요 고치겠읍니다

2022-11-09 10:43 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +extension ArtistRegisterViewController: RegisterRegionDelegate, RegisterGearsDelegate, RegisterTextInfoDelegate, RegisterPortfolioDelegate {
모두들 다 할 수 있어요 어렵치 않아요

2022-11-09 10:44 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +            self.delegate?.cameraBodySelected(cameraBody: textField.text ?? "카메라 바디")
텍스트 필드에서 받은 text 를 위임자인 delegate 에 넘겨주기 위한 겁니다. 내부에서 이어주는 요소에 프로토콜을 이었다고 생각하면 됩니다잇

2022-11-09 10:44 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +        view.addSubviews(RegisterGearsViewController.mainTitleLabel, subTitleLabel, bodyTitleLabel, cameraBodySectionLabel, cameraBodyExampleSectionLabel, cameraBodyTextField, cameraLensSectionLabel,
확인입니닷

2022-11-09 10:47 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
> +    private let mainTitleLabel = UILabel().then {
확인했습니다. 바빠서 extension 된 것까지 해서 바꿀 힘이 없었습니다ㅜ

2022-11-09 10:47 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/GridCollectionViewFlowLayout.swift
> +//
헉 이게 무야 지우겠습니다

2022-11-09 10:58 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +
각 요소별로 MARK: - 로 표시 해놨습니다

2022-11-09 10:58 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +    private var portfolioImageData: [UIImage] = []
서버로 보낼 데이터 셋을 미리 구현해봤습니다

2022-11-09 10:58 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +        pageFivePortpolio.delegate = self
delegate 을 선언해서 데이터를 받을 수 있게 만들었습니다.
collectionView.delegate = self
collectionView.datasource = self 
라고 생각하시면 됩니다

2022-11-09 10:58 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +    }
코비와 상의한 결과, VC 안에 VC 가 있으면 최상위 VC 에 Noti 를 쓰는 것이 좋아보입니다.
이후에 분기처리를 하여 사용하면 조금 복잡하겠지만, 쓸 수 있습니다.

⭐️ VC 안에 VC 를 많이 넣지 맙시다. 코드가 지저분해지고 힘들어집니다

2022-11-09 10:58 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +
상위 VC 에서 다 조작할 수 있게.... 이렇게 했고 static 으로 받아서 사용했습ㄴ비다

2022-11-09 11:18 UTC, PecanPiePOS reviewed
볼륨이 많이 큽니다. 읽느라 고생 많앗습니다들
다임 짱

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +            }
마지막 페이지에서, 앞 항목들이 다 적혀져있는지 확인해서 넘어갈 수 있을지 말지 체크하는 로직입니다.
복잡한데 이거를 줄일 수 있으신분 계시면 알려주세요 배울게욧

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
> +    private let mainTitleLabel = UILabel().then {
근데 이렇게 쓰면 추가적으로 프로퍼티를 선언하고 싶을 때는 못하지 않나요?

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +    // 5. 글자 제한 수를 둬야 한다.❓
이렇게 매 파일마다 다음 버전에 업데이트할 요소를 체크했습니다.

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
>  import Then
PHPicker 를 사용하기 위해서는 PhotosUI 를 임포트해야합니다.
(네이티브에욧)

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +    }
인스타처럼 3단으로 만드는 코드인데,
더 간단하고 정확하게 만드실 수 있으신분 알려주세요!

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +    }
⭐️ PHPicker 는 access permission 이 필요 없습니다. privacy photolibrary 를 사용하지 말라고도 권유하고 있습니다. (애플 다큐)
PHPicker 는 초기화를 그냥 할 수 없습니다.
꼭 PHPickerConfiguration 을 먼저 인스턴스화 해서 내부 프로퍼티들을 설정하고 그 다음, 그 configuration 을 통해 초기화를 해야합니다.

>  photoConfiguration.selectionLimit = 12
는 사진 개수를 고를 수 있는 개수 제한을 뜻합니다.

>  photoConfiguration.filter = .images
는 library 에서 어떠한 형태의 asset 을 가져올지 정합니다. 다른 항목에는 livephoto 와 video 가 있습니다.

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +        }
PHPicker 는 기본적으로 한번만 사용하고 넘어가게 만들어진 것으로 알고 있어서 delegate 이 딱 하나 밖에 없는 것 같습니다. (화!남!)
사진을 가져오는 로직입니다. 거의 정해진 포맷에서 조금조금씩 바뀌어서 쓰이고 있는듯 합니다.

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +}
콜렉션 뷰에서 마지막 cell 만 기능이 다른 cell 을 구현하고 싶다면 이걸 보시면 됩니다.
1. count 를 +1 을 해야 합니다.
2. tag 나 다른 identifier 를 사용해서 cell 의 종류를 바꿔도 되지만 저는 크게 어렵지 않은 count 를 기준으로 cell 을 나눴습니다.

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +        }
마지막 cell (+) 을 누르면 PHPicker 를 쓸 수 있습니다.

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/Views/RegisterAddPhotosCollectionViewCell.swift
> +
포트폴리오 collectionView 에서 +버튼을 나타내는 cell 입니다.

2022-11-09 11:18 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/Views/RegisterPortfolioImageCell.swift
> +
포트폴리오 collectionView 에서 사진에 해당하는 cell 입니다.

2022-11-09 13:07 UTC, obtusa07 commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
>              $0.bottom.equalToSuperview().inset(UIScreen.main.bounds.height/13)
이 부분 좋네요. 시간이 쓸데없이 소모되는게 오토레이아웃을 어떻게 설정할지에 대한 것이었는데 뷰 기준으로 수학적으로 계산해서 잡는게 제일 좋은거 같습니다.

2022-11-09 13:18 UTC, obtusa07 commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +    }
compositional layout을 쓰면 되는데 무조건 써야하는 상황은 아닌거 같아요. 충분히 FlowLayout으로도 만들 수 있고요. 오히려 코드 길이는 더 길어질거 같습니다.

2022-11-09 13:24 UTC, obtusa07 commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +}
제가 찾던 마지막 셀 + 기능 여기있네요!

2022-11-09 13:37 UTC, obtusa07 commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterWelcomeViewController.swift
> +    private func configUI() {
p3
저희가 UI 설정을 위한 메서드의 이름을 통일하지 않긴 했는데 configureUI가 정상적인 네이밍으로 보이는데 왜 config로 수정한걸까요?

2022-11-09 13:39 UTC, obtusa07 approved these changes
많이 배웠습니다!

2022-11-09 14:44 UTC, coby5502 approved these changes
LGBT

2022-11-09 14:44 UTC, coby5502 commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +            $0.height.equalTo(view.bounds.height/12)
p5
계산들어가는 부분, 따로 Enum으로 빼면 깔끔할거 같습니다,

2022-11-09 14:44 UTC, coby5502 commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +extension ArtistRegisterViewController: RegisterRegionDelegate, RegisterGearsDelegate, RegisterTextInfoDelegate, RegisterPortfolioDelegate {
징그럽네요

2022-11-09 14:44 UTC, coby5502 commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +    }
제 메인화면의 컬렉션뷰 코드를 참고하세요! enum으로 빼면 깔끔합니다!

2022-11-09 14:44 UTC, coby5502 commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +}
저도 MC2 메인화면을 비슷하게 만든 기억이 있네요.

2022-11-09 14:44 UTC, coby5502 commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterWelcomeViewController.swift
> +    private func configUI() {
저는 빈센트 시대(?)부터 통일한거로 기억합니다만,,,

2022-11-09 14:52 UTC, Rookie0031 requested changes
## 고생하셨슴다!!

delegate pattern을 적용하시다니 짱짱입니다
꼼꼼하고 정돈된 코드 감사합니당

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
>              $0.bottom.equalToSuperview().inset(UIScreen.main.bounds.height/13)
한번 나눠주면 비율적으로 편합니당...

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +            $0.height.equalTo(view.bounds.height/12)
오호... 이 부분은 다음 테스크에 넣겠습니다 좋은거같네요

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +    deinit {
제가 배운바로는 기본적으로 deinit 을 하지 않으면 네비게이션으로 이어지는 뷰에서 다 Noti가 되는걸로 알고있는데,
안전하게 deinit 을 하면 좋지 않을까 싶습니다.

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +extension ArtistRegisterViewController: RegisterRegionDelegate, RegisterGearsDelegate, RegisterTextInfoDelegate, RegisterPortfolioDelegate {
징그러워도 조금 참으십시오

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterConfirmViewController.swift
> +    private let mainTitleLabel = UILabel().then {
오호... 생각해보니 그러겠네요. 귯귯

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +        $0.clipsToBounds = true
음 사실 그냥 쓰던거라 필요할거라는 생각만 있었었는데 이건 까먹었네요. 찾아보고 테스트해보겠습니다

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
키보드 말고 다른 곳을 누르면 키보드가 내려오는 함수입니닷

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +        case 1:
태그가 switch 문에서 편하게 쓸 수 있습니다.

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterGearsViewController.swift
> +protocol RegisterGearsDelegate: AnyObject {
그래서 이거에 대해서 Protocol 폴더가 있는데, 혹시 빨간색으로 표시되어 있지 않나요? 그래서 일단 따로 넣어놨습니다.

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +    // TODO: (다음 버전에..) 1.PHPickerView 에서 취소 버튼을 누르면 없어지는 거 -> 어떻게든 로직짜서 만들어봐
확인입니다!

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +    }
이것도 확인하겟습니다!

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +
네네 그 delegate 을 받는 대상이 달라져서 개행했습니다.

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
> +            photoItem.loadObject(ofClass: UIImage.self) { photos, _ in
확인했습니다. Error 를 추가하겠습니다.
추가적으로, .localizedDescription 은 안 넣겠습니다. 그 이유는 error 만 print 해야 조금 더 구체적인 정보를 얻을 수 있어서 그렇습니다.

2022-11-10 02:37 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterWelcomeViewController.swift
> +    private func configUI() {
헉 그랬나요 왜 전 configUI 가 맞다고 생각이 든거였지..! 확인하고 다음 테스크때 다 바꾸겠습니다

2022-11-10 03:02 UTC, Rookie0031 approved these changes

2022-11-10 05:15 UTC, merged