💄 ArtisTappedView의 UI를 수정했습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #52
Opened 2022-11-15 12:36 UTC by Rookie0031

## 🌁 배경
지난 회의에서 논의된 UI 수정 요소들을 수정했습니다. 
네비게이션바를 커스텀해서 당근 마켓의 view와 비슷하게 구현되었고 하단의 문의하기가 있는 view는 에어비앤비를 참고했습니다. 

## 👩‍💻 작업 내용 (Content)
디테일 화면 (ArtistTappedView)
- [x] 작가 관련 정보 맨 앞에 SF symbol 넣기
- [ ] 데이터 모델 고려해서 지금 데이터 바꾸기 
- [x] 네비 기능을 넣은 버튼들을 최상단에 넣자 (네비바 말고 그냥 네비바 자리에 커스텀으로 넣기)
- [x] 아래 그리드 뷰에서 사진 탭하면 전체화면으로 보인다.
- [ ] 이름 아래에 # 영역은 자유 입력으로 하기 => 작가 등록 뷰 데이터에 맞추기
- [x] 문의하기 버튼을 포함하는 뷰 수정 
        (에어비앤비 따라서 맨위에 line 넣고, 문의전 체크해야되는 중요 정보( ex. 상호페이) 를 왼쪽으로 그리고 오른쪽에는 문의하기 버튼)

## 📱 스크린샷
https://user-images.githubusercontent.com/103009135/201920656-ac3d0d69-f25b-4f36-a251-f9a803d09bfc.mov

## 📣 PR & Issues
#9 

## 추후 개발 사항
- 이미지리스트 URL 리스트를 활용한 비동기 통신 로직 구현
- headerView size 재조정하는 과정의 UX 개선 (이미지 로딩 동안 스켈레톤으로 처리예정)

2022-11-15 12:38 UTC, Rookie0031 commented on Flicker/Global/Extensions/UITextView+Extension.swift
> +extension UITextView {
TextView의 자간과 행간을 조절할 수 있는 extension입니다.

2022-11-15 12:38 UTC, Rookie0031 commented on Flicker/Network/NetworkManager.swift
> +    let portFolioImageList: [String] = [
이전 뷰에서 다음과 같은 이미지 URL 배열을 받아올 것이라서 dummy 데이터로 테스트하기 위해 넣어놓은 URL입니다. (추후 이미지 통신 로직에서 사용될 예정)

2022-11-15 12:39 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    private var headerHeight: Int = 700
collectionView의 headerView는 높이를 지정해줘야합니다. 그래서 처음에 기본으로 700으로 세팅한뒤 뷰가 그려진 이후에 headerView내의 subview의 높이를 모두 더해서 새롭게 높이를 재조정합니다.

2022-11-15 12:41 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    private func resetHeaderViewSize() {
headerView의 크기를 계산해서 재조정하는 함수입니다.

2022-11-15 12:47 UTC, Rookie0031 commented on Flicker/Global/Base/BaseViewController.swift
> +    func setupBackButton() {
setupBackButton을 오버라이드하고 싶었는데 private이라 할 수 없엇읍니다.. 그래서 private을 빼게 되었습니다.

2022-11-15 15:45 UTC, PecanPiePOS requested changes
고생하셨습니다 루키!

2022-11-15 15:45 UTC, PecanPiePOS commented on Flicker/Network/NetworkManager.swift
> +    let portFolioImageList: [String] = [
p4
그러면 이 NetworkManager 코드 하단에 위치한 urlSession 들은 Firebase 코드가 들어오면 사라지는 건가요?

2022-11-15 15:45 UTC, PecanPiePOS commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    private var headerHeight: Int = 700
p4
700인 이유가 있을까요?? 다른 500이나 1000이 아닌 700인 이유가 있을까요?!

2022-11-15 15:45 UTC, PecanPiePOS commented on Flicker/Screens/Artist/HeaderCollectionReusableView.swift
> -    }
p2
카메라 장비 관련해서는 보통 카메라 바디 -> 렌즈 순으로 이야기를 많이 합니다.
그래서 deviceInfo 와 lensInfo 의 위치가 바뀌어야 합니다!

2022-11-15 15:45 UTC, PecanPiePOS commented on Flicker/Screens/Artist/HeaderCollectionReusableView.swift
> +    private let regionInfo = UILabel().makeBasicLabel(labelText: "서초구, 서대문구, 은평구", textColor: .black, fontStyle: .callout, fontWeight: .light)
p3
루키가 올려주신 화면을 보고서 말씁드립니다!
지역부터, 카메라 정보 2개까지 약간 위의 자기 소개와 구분이 가지 않는 점이 있다고 생각이 듭니다.
font size 또는 text color 중 하나를 바꿔서 구분을 뒀으면 좋겠는데 아무래도 text color 를 바꾸는게 좋을 것 같다는 생각이 들어서 지역, 바디, 렌즈 정보의 text color 를 .alpha 를 주거나 아니면 아예 .systemgray 를 줘서 차이를 주면 좋을 것 같습니다.

2022-11-16 00:30 UTC, Rookie0031 commented on Flicker/Network/NetworkManager.swift
> +    let portFolioImageList: [String] = [
네 거의다 없어질 예정입니다.. 지금은 query하는 거로 되어있는데 그냥 데이터 받아오는거로 바뀔 거고 completion handler 구조는 최대한 없애고 async await로 대체할 생각입니다!

2022-11-16 00:32 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    private var headerHeight: Int = 700
700인 이유는 없습니다 ㅋㅋㅋㅋ 처음에 피그마에 써진 텍스트를 넣고 그 높이를 맞춰보니 700쯤 나온 거라서.. 이건 자유롭게 바꿔도 됩니다

2022-11-16 01:39 UTC, obtusa07 approved these changes
힘써주셔서 감사합니다

2022-11-16 01:39 UTC, obtusa07 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    private lazy var collectionView = UICollectionView(frame: .zero, collectionViewLayout: portfolioFlowLayout).then { $0.contentInsetAdjustmentBehavior = .never
p4
줄바꿈이 기괴하게 되어있군요...

2022-11-16 01:39 UTC, obtusa07 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    //TODO: 출시 후, 앱스토어 링크 넣을 예정
p5
앱스토어 링크가 뭔가요? 여기에 왜 들어가죠??

2022-11-16 01:39 UTC, obtusa07 commented on Flicker/Screens/Artist/ImageViewController.swift
> +    private let imageView = UIImageView().then {
p3
이 부분과 관련하여 대화를 나눠봤는데 사진의 비율을 일그러트리는게 좋아보이지 않아. 루키와 Airbnb의 ImageViewController를 보면서 이야기를 나눴습니다. Airbnb는 scaleAspectFit을 이용하고 있는걸로 보입니다. 그리고 option으로 밑에 사진에 대한 캡션을 달수도 있고요

2022-11-16 05:54 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +    //TODO: 출시 후, 앱스토어 링크 넣을 예정
아 좋은 질문이네요 
작가 디테일뷰에서 우측상단에 공유하기 버튼이 추가될 예정입니다. 공유하기 버튼에 앱스토어 링크를 달아서 카톡, 에어드랍으로 앱스토어 링크 공유할 수 있게 하려고합니다

2022-11-16 12:58 UTC, Rookie0031 commented on Flicker/Network/NetworkManager.swift
> +        if let cachedImage = cachedImages.object(forKey: url as NSString) {
맨 처음에 이미지를 불러올 때 캐시에 있으면 불러오는 코드입니다

2022-11-16 12:58 UTC, Rookie0031 commented on Flicker/Network/NetworkManager.swift
> +            try await self.cachedImages.setObject(data as NSData, forKey: url as NSString)
URL로 이미지 데이터를 요청하고 받아오면 캐시에 NSData형식으로 저장합니다

2022-11-16 12:59 UTC, Rookie0031 commented on Flicker/Network/NetworkManager.swift
> +        try await withThrowingTaskGroup(of: (UIImage).self) { group in
작가 포트폴리오 이미지가 여러개라서 동시에 통신을 하려면 태스크를 그룹으로 묶어서 처리해야합니다. 그것과 관련된 코드입니다

2022-11-16 13:33 UTC, coby5502 approved these changes
네트워크 코드 나중에 강의해주시죠

2022-11-16 13:33 UTC, coby5502 commented on Flicker/Screens/Artist/ArtistPortfolioCell.swift
>      "ArtistPortfolioCell"
p3
final class로 선언하는건 어떨까요?
그리고 identifier을 굳이 선언안해도 될 것 같아요!
나중에 `ArtistPortfolioCell.identifier`대신 `ArtistPortfolioCell.classname`으로 해도 되거든요!

2022-11-16 13:33 UTC, coby5502 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +        statusBarBackGroundView.translatesAutoresizingMaskIntoConstraints = false
p3
이 부분은 왜 snapkit으로 하지 않으셨나요?

2022-11-17 04:39 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistPortfolioCell.swift
>      "ArtistPortfolioCell"
반영완료 떙큐!

2022-11-17 04:39 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +        statusBarBackGroundView.translatesAutoresizingMaskIntoConstraints = false
아 이게 safeArea에다가 constraint을 걸고싶은데 스냅킷으로하니까 잘 안되서 걍 안썻습니다..

2022-11-17 04:40 UTC, Rookie0031 commented on Flicker/Screens/Artist/HeaderCollectionReusableView.swift
> +    private let regionInfo = UILabel().makeBasicLabel(labelText: "서초구, 서대문구, 은평구", textColor: .black, fontStyle: .callout, fontWeight: .light)
alpha 효과가 so chill 하군요 반영완료 땡큐!

2022-11-17 04:40 UTC, Rookie0031 commented on Flicker/Screens/Artist/HeaderCollectionReusableView.swift
> -    }
반영완료 떙큐!

2022-11-17 05:53 UTC, PecanPiePOS approved these changes

2022-11-17 06:01 UTC, merged