✨ 비밀번호 재설정 기능 추가했습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #68
Opened 2022-11-18 08:33 UTC by Kim-Yeon-ho

## 🌁 배경
- 둘러보기 기능을 삭제하며, 그 빈공간에 무엇을 채워야 하나 고민을 했습니다.

- 생각해보니 비밀번호 찾기 기능자체가 없으면 앱스토어에서 통과가 어려울 것이라는 저의 생각으로 파이어베이스 로그인에 비밀번호 재설정기능을 추가하게 되었습니다.

## 👩‍💻 작업 내용 (Content)
- 뒷 배경이 불투명한 VC로 팝업처럼 보이는 뷰를 추가하여 이메일을 입력하도록 작업했습니다.

- 이메일을 입력하고 올바른 이메일일 경우 메일이 보내지며, 입력한 이메일에서 비밀번호 재설정을 할 수 있는 링크를 받습니다.

- 이 후 링크를 통해 재설정한 비밀번호로 다시 이용이 가능합니다.

- 화면녹화 동영상입니다 죄송함둥

- 로그인 관련 작업을 하면서 얼럿이 뜨는데 화면이 넘어가는 버그를 바로 해결했습니다.

## 📱 스크린샷
<p align="left">
  <img width="300" alt="스크린샷1" src="https://user-images.githubusercontent.com/81131715/202655821-5f710d15-2f16-40bd-ae13-d4ac612deaba.gif">
</p>

https://user-images.githubusercontent.com/81131715/202655957-1d29bf47-6574-4385-92c8-4900f70e41ff.mov

## ✅ 테스트방법
- Cmd + R

## 📣 PR & Issues
- 

## 📬 참고문서, 레퍼런스
- https://firebase.google.com/docs/auth/ios/manage-users

2022-11-18 08:45 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/LoginViewController.swift
> +            if let userId = await FirebaseManager.shared.signInUser(email: email, password: password) {
guard let 에서 if let으로 바꾼 이유는 로그인에 실패했을 경우 단순 확인 후 코드 종료가 아닌
제가 원하는 건 로그인에 실패를 했을 때 Alert을 띄워 사용자가 한번 더 확인하도록 하기 위함이여서 if let으로 바꿔줬습니다.
전에 로그인에 성공하더라도 Alert이 떳던 이유도 guard let일때 alert을 사용하기 위해서 메소드의 마지막에 alert코드를 넣어놨어서 로그인에 성공을 해도 뜨게 됐습니다.

2022-11-18 08:45 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +            Auth.auth().sendPasswordReset(withEmail: emailField.text ?? "" ) {(error) in
이메일을 보내는 클로져로 이메일 유효성 검사를 통과 했을때 작동하게 됩니다.
실패를 하면 Alert을 통해 이메일을 확인하라는 알림을 주고 성공했을 시에는 다시 로그인 화면으로 나가게 됩니다.

2022-11-18 18:14 UTC, coby5502 approved these changes
테스트 방법이 신박하네요.

2022-11-18 23:52 UTC, Rookie0031 commented on Flicker/Screens/Login/LoginViewController.swift
> +            if let userId = await FirebaseManager.shared.signInUser(email: email, password: password) {
LGTM

2022-11-18 23:54 UTC, Rookie0031 commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +            Auth.auth().sendPasswordReset(withEmail: emailField.text ?? "" ) {(error) in
p5

클로저 파라미터가 error하나인데 ( ) 괄호를 빼면 좋을거 같습니다~

2022-11-19 00:04 UTC, Rookie0031 approved these changes
## 고생하셨습니다!!

사소한 리퀘스트가 있지만 말그대로 사소해서 approve 합니다

2022-11-19 00:04 UTC, Rookie0031 commented on Flicker/Screens/ProfileSetting/InputPassword/InputPasswordViewController.swift
> +//        appleLoginReAuthUser()
p3

아래 코드에서 이런 점들을 수정하면 좋을거같아요

1. didTapSignInButton 이라고 네이밍되었는데 그냥 봤을 때는 로그인 버튼을 눌럿을때 작동되는 함수 같아서 네이밍 수정을 하면 좋을 거 같습니다 ( 프로필에서 자기 프로필 수정하려고 클릭하면 실행되는 함수 맞죠??)
2.  reauthenticate 함수를 써서 error가 없으면 프로필로 넘어가도록 하는데 Task가 쓰였는데요, 네비게이션 과정은 비동기로 Task안에서 처리할 이유는 없을거같아서 Task를 빼도 좋을 거 같네요

https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/blob/a52ba54eafbb90f8144c1f73427d4e88dc988ec1/Flicker/Screens/ProfileSetting/InputPassword/InputPasswordViewController.swift#L110-L136

2022-11-19 05:15 UTC, PecanPiePOS requested changes
고생했습니다 끝이 보입니다. 
로그인팀 화이팅!

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +        }
p3
팝업 뷰 자체의 height 를 조금 더 늘려야 할 것 같습니다. 버튼의 크기도 너무 작고,
"이메일 주소를 확인해 주세요" 라는 라벨이 버튼과 너무 가깝게 붙어있습니다. 

-> $0.height.equalTo(UIScreen.main.bounds.height * 0.45) 정도로 바꾸는 것을 추천 드립니다!

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +            $0.trailing.equalTo(emailField.snp.centerX).offset(-10)
p3
.offset(-5) 로 바꾸는 것을 추천 드립니다.

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +            $0.trailing.equalTo(emailField.snp.centerX).offset(-10)
p3
top 도 .offset(35) 정도로 바꾸는 것을 추천 드립니다!

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +            $0.trailing.equalToSuperview().inset(30)
p3
위의 sendEmailButton 과 동일하게 부탁드립니다!

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +    }
p3
저는 오히려 "나가기" 버튼이 회색이어야 하지 않나 생각이 듭니다.

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +    }
p3
"나가기" 버튼 보다 조금 더 어두운 색을 사용하여 구분을 두었으면 좋을 것 같다는 생각이 듭니다.

2022-11-19 05:15 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +    }
보내기 버튼이 활성화 되었을 때, 같은 분홍색을 띄는 것은, ux 적으로 어떤 것이 더 highlight 되어있는지 헷갈릴 것 같습니다!

2022-11-19 07:16 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +        }
@PecanPiePOS 
![Simulator Screen Recording - iPhone 14 Pro Max - 2022-11-19 at 16 15 21](https://user-images.githubusercontent.com/81131715/202839585-9deedaa2-2b74-43f9-b08b-d2c8f058f085.gif)
UI수정사항 반영한 부분입니다 확인해주시고 comment남겨주세요 :)

2022-11-19 07:22 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +        }
고생했습니다! 
딱 한번만 더 수정 부탁드립니다!

height * 0.35 로 바꿔주시고, 
"보내기" 버튼의 .normal 상태에서의 color  "나가기" 버튼의 .normal 상태 컬러보다 더 진한 색으로 바꿔주시면 끝날 것 같습니다!

2022-11-19 07:28 UTC, Kim-Yeon-ho commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +        }
@PecanPiePOS 
![Simulator Screen Recording - iPhone 14 Pro Max - 2022-11-19 at 16 26 46](https://user-images.githubusercontent.com/81131715/202839985-82b0e153-3441-46bc-a554-a04a715e7984.gif)

2022-11-19 07:29 UTC, PecanPiePOS commented on Flicker/Screens/Login/ResetPassword/PopUpViewController.swift
> +        }
기가 막힙니다. 👏

2022-11-19 07:29 UTC, PecanPiePOS approved these changes

2022-11-19 07:59 UTC, merged