🐛 ArtistTappedView UI 및 이미지 로드 관련 버그를 수정했습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #70
Opened 2022-11-18 09:57 UTC by Rookie0031

## 🌁 배경
머지 이후 

## 👩‍💻 작업 내용 (Content)
#### 1. 맨 처음 뷰를 그릴 때 헤더뷰가 없어지는 문제 해결
헤더뷰의 사이즈를 reset하는 함수를 reloadData가 확실하게 끝난 후 실행되도록 조정하였습니다.

#### 정확한 이유는 찾지못했지만 collectionView에서 reloadData과정과 헤더뷰를 등록하는 과정이 동시에 발생하는 것으로 추정됩니다. 
reloadData가 끝나야 그려진 헤더뷰의 subview를 기반으로 헤더뷰 사이즈를 재조정할 수 있는데  reloadData 과정 중에 헤더뷰 사이즈가 넘어오지 않은 상태로 뷰를 그리기 때문에 맨 처음 뷰를 그릴 때 헤더뷰가 그려지지 않은 것으로 생각됩니다.

#### 2. 캐싱 이미지를 가져올 때마다 이미지 리스트의 순서가 바뀌는 문제
이미지 통신 속도를 최적화하기 위해서 여러 장의 이미지를 병렬적으로 (동시에) 통신해서 가져오는 절차를 거치게 됩니다. 
#### 문제는 이 때 이미 다운로드되서 캐싱처리된 이미지를 로드해올 때도 병렬적으로 가져오기 때문에 실제 UIImage 배열의 순서가 그 때 그 때 마다 다르게 됩니다. 
( 캐시에서 이미지를 찾아서 가져오는 과정이 동시에, 비동기적으로 이루어지기 때문에 ABC, BAC, CBA 등으로 순서가 무작위로 들어오게 되는 것으로 추정합니다.)

결과적으로 원래는 withThrowingTaskGroup 이라는 함수를 써서 하나의 Task 안에 여러 subTask를 그룹으로 묶어서 병렬처리하는 구조였는데 이제는 병렬이 아닌 하나하나 이미지를 다운로드 하는 형태로 바뀌었습니다. 하지만 이미지가 몇장안되서 그런지 눈에 띄는 속도저하는 없었습니다 ㅎㅎ..

#### 3. 아이폰 pro max일 때 collectionView Cell의 배치가 깨지는 문제
collectionView는 셀의 격자형 배치를 위한 레이아웃 옵션으로 flowLayout을 가지고 있습니다. flowLayout에는 셀의 크기에 상관없이 최소한의 간격을 유지하도록 조정하는 minimumInteritemSpacing 이라는 프로퍼티가 있는데요, 이걸 너무 크게 조정해서 발생하는 문제였습니다.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103009135/202671523-64b0c4b9-4c53-4bb0-88b3-c0ce36f66e91.png">

셀의 크기를 기기 화면 크기에 비례해서 커지게 두었는데, 셀간 가로방향 최소간격은 상수로 두었기 때문에 그 최소의 간격을 유지하기 위해서 셀들이 2열 3행 형태로 바뀌게 된 것입니다.

그래서 이 최소 간격을 조절해서 문제를 해결했습니다.

#### 4. 뒤로가기로 메인뷰로 돌아갔을 때 탭바가 없어지는 문제
작가 디테일뷰는 탭바가 하단에 있을 필요가 없어서 뷰를 그릴 때 configUI 함수에 탭바를 숨기는 코드를 추가했었는데, 뷰가 없어지면 다시 원래대로 돌려놔야했습니다. 그래서 viewLifeCycle을 담당하는 함수 중 적절한 곳에 탭바를 다시 보여지게 하는 코드를 추가했습니다.

추가로 작가 디테일뷰에서 이미지를 클릭하면 이미지가 전체화면으로 잡히고 다시 돌아올 때는 completion 클로저에 탭바를 없애는 코드를 추가했습니다. 그래서 ImageViewController가 없어지고 다시 작가 디테일뷰로 돌아왔을 때도 탭바를 숨길 수 있게 처리했습니다.

#### 그 외 사항
작가 디테일 뷰에서 개별 이미지 클릭시 전체화면이 되었을 때 이미지 비율이 깨진다는 의견이 있었습니다. contentMode를 aspectFit으로 변경해서 해결했습니다.

## 📱 스크린샷
https://user-images.githubusercontent.com/103009135/202673586-feda9859-ebf4-499b-95d0-fefc44baca65.mov

## ✅ 테스트방법
MainViewController 파일의 맨 마지막 함수 (didSelectItem 이 있는 collectionView delegate 함수)에 네비게이션 관련 코드를 추가해서 테스트 해볼 수 있습니다.

=> navigationController?.pushViewController(ArtistTappedViewController(), animated: true)

## 📣 PR & Issues
#67

2022-11-18 10:04 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
asyncAfter 메소드를 사용해서 시간차를 두고 코드가 실행되게 할 수 있습니다. 이러면 reloadData가 다 끝난 뒤에 resetHeaderView 함수가 수행되도록 순서를 조정할 수 있습니다. 만약 asyncAfter로 0.1초의 시간 딜레이 처리가 없으면 맨 처음 heaerView를 그릴 때 크기가 0으로 잡혀버립니다. collectionViewData가 reload되고 0.1초가 지나고 headerView 사이즈가 재조정되므로 원래 viewDidAppear에서 헤더뷰 사이즈를 재조정하는 구조로 하였을 때 일시적으로 레이아웃이 깨지는 현상을 막을 수 있습니다.

참고로 0.1초는 그냥 임의로 잡은 시간입니다.

2022-11-18 18:11 UTC, coby5502 requested changes
0.1초의 시간을 주고, 헤더 사이즈 함수 실행시키는 것은 반대합니다!

2022-11-18 18:11 UTC, coby5502 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
p1
시간을 줘서 동작의 순서를 임의로 주는 것은, 매우 위험하다고 생각합니다.
reloadData()가 끝나고 나서, 바로 resetHeaderViewSize가 실행되도록 하는 다른 코드가 있을 겁니다. 아니 그래야합니다!
찾아보겠습니다. 기다려주세요

2022-11-18 18:17 UTC, coby5502 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
>              }
```suggestion
            self.collectionView.reloadData()
            self.collectionView.performBatchUpdates {
                self.resetHeaderViewSize()
            }
            
            
```

2022-11-18 23:49 UTC, Rookie0031 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
수정했습니다 감사합니다! 

그런데 강제로 시간차를 줘서 reload가 끝나고 실행되는 completion 역할을 만드는건 좀 이상하다고 느끼긴했는데 매우 위험하다고 생각한 이유는 뭔가요?? 검색했을때는 별 다른 위험케이스는 나오지 않아서 궁금합니다

2022-11-19 04:58 UTC, coby5502 commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
뇌피셜이긴 하지만, reloadData()가 0.1초 안에 안 끝날 경우에는 순서가 꼬일 거라고 생각합니다.
물론 그런 경우는 많지 않을 거라고 생각합니다!

2022-11-19 04:59 UTC, coby5502 approved these changes
가즈아

2022-11-19 05:18 UTC, PecanPiePOS commented on Flicker/Screens/Artist/ArtistTappedViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.1) {
좋은 의견이네요. 그런데 그렇게 꼬일 때, 어떤 일이 일어나는지 궁금하네요. 실험해봐야겠어요

2022-11-19 05:22 UTC, PecanPiePOS approved these changes
사진의 순서에 대해서는 받아온 다음에 .sorted 를 해도 괜찮지 않을까 합니다.
고생했습니다!

2022-11-19 08:17 UTC, Kim-Yeon-ho approved these changes

2022-11-19 08:33 UTC, merged