⚡ 작가 등록 화면에서 Firebase 업로드 기능 구현 및 속도를 향상 시켰습니다.
DeveloperAcademy-POSTECH/MacC-Dime-Flicker pull request #71
Opened 2022-11-18 13:11 UTC by PecanPiePOS

## 🌁 배경
- 로딩뷰가 있는게 더 자연스러워 보여 로딩뷰를 구현했습니다.
- 사진 작가가 올리는 사진들을 Firebase 에 업로드를 시킵니다. 
- 기존의 업로드 하는 코드는 하나의 사진을 올리는 코드라 비동기로만 처리했는데, 여러 사진을 올리기 위해 기존 코드를 Task 하나에 올려 사용하니, Sub Thread 에서 Sequence 를 가지고 동작했습니다. 500kb 가 되지 않는 사진 하나를 업로드 하는데에 거의 2~3초의 시간 비용이 발생했고, 이는 UX 상 문제가 되는 일임을 인지했습니다. 업로드 속도 향상이 필요했습니다.

## 👩‍💻 작업 내용 (Content)
- [x] 로딩뷰 구현
- [x] Firebase Storage 에 Image 를 압축하여 저장
- [x] 동시에, downloadURL 을 String 으로 저장
- [x] Concurrency (async let, await) 을 사용하여, 업로드 속도 향상

-----
### ⚠️ asynchronous != concurrent ⚠️
> ⭐️ **비동기와 동시성은 다릅니다.** ⭐️

제가 노션에 정리한 글을 그대로 따오자면...

> "

<img width="692" alt="Screenshot 2022-11-18 at 10 07 48 PM" src="https://user-images.githubusercontent.com/89404664/202712370-e3c7d0a8-a347-49eb-bcd5-8ac3c205f924.png">

 기존의 사진 업로드 코드는 디버깅창에서 확인했을 때, 비동기적인 작업은 맞지만, Sub Thread 에서 Sequence 를 가지고 작업하는 코드였다.

 기존의 코드에서 볼 수 있듯, 받아온 [UIImage] Array 를 Iterate 하며 업로드하기 위해 `.asyncForEach()` 라는 Sequence Extension 의 함수를 썼는데, 여기서도 알 수 있듯 async 하지만 *concurrent 하지는 못했다.*

 즉, await 가 사진을 업로드 하는 작업마다 걸려 있었다. 이 말은 동시에 사진을 올리지 못하고, 사진 하나가 업로드 되는 시점을 기다리며, 뒤의 다른 사진들은 suspend 되어 작업을 중지하고 있음을 뜻한다. 그래서 사진 개당 3초 정도의 시간이 소요되며 5장의 사진을 올리면 14초 정도의 시간이 흐르고 업로드가 마무리 되었다.

-----
개선 후...
https://github.com/DeveloperAcademy-POSTECH/MacC-Dime-Flicker/blob/2b8efbedec5c7778dfe5b3dd966d0d75a2873fa0/Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift#L242-L260

Firebase 에 업로드 하는 메서드는, UIImage Array를 받아 해당 Image 의 Url 의 String Array 를 리턴하는 형식이었다. 이를 하나의 UIImage 를 받고 해당 Image 의 Url String 을 리턴하는 형식으로 바뀌었는데,  Main Thread 가 아닌 **비동기**로 돌린다는 `async` 에, `putDataAsync()`, `reference.downloadURL()` 을 `await` 로 받으며 이 작업들에 대해서는 suspend 를 하여 작업 마무리를 하고 간다라는 기본적인 내용은 크게 바뀌지 않는다.

 크게 바뀌는 점은, 이 함수를 실행하는 부분에서 크게 차이가 있다. 기존의 실행은 Task 하나로만 Array 를 Array 로 리턴한다는 단 한번의 실행 과정이 있었다. 즉, 이곳에서 비동기적이지만 동시적으로 작업을 하지 못해, Sub Thread 에서 Sequence 가 발생하여 시간이 오래 걸렸던 것이다.

 **그래서 Concurrent 한 작업을 만들기 위해 쓰인 `async let` 과 `await` 를 사용했고, `Task{}` 안에 넣어 Iterate 했다. 하나의 `Task{}` 안에, 하나의 비동기 작업이 들어갈 수 있게 했다.**

 Task {} 하나가 Thread 하나를 먹는다고 생각하면 좋다. 그러므로 Task 를 여러개 써보자.

 → 그러자 로딩 view 를 만든게 무안할 정도로 빠른 속도로 업로드가 완료되었다. 대략 0.3 ~ 0.5초 만에 작업이 끝났다.

단지, 하나의 공유자원에 동시에 접속하는 것이 살짝 마음에 걸린다. 오히려, .append 하나라서 상관이 없으려나?

-----

**결론: Concurrency 를 사용하여 5장의 사진을 업로드 하는데에 드는 시간 비용을 14초에서 0.4 초로 단축했습니다.**

-----

## 📱 스크린샷

### 업로드 개선 前
https://user-images.githubusercontent.com/89404664/202710064-1a73573e-e98d-4be6-a2fc-c0d46e5b6a8f.MP4

!!
### 업로드 개선 後
https://user-images.githubusercontent.com/89404664/202711145-4eaa4e12-df3a-41fd-ae5d-17ebd3cac6e3.mp4

## ✅ 테스트방법

## 📣 PR & Issues
#61 

## 📬 참고문서, 레퍼런스
https://www.youtube.com/watch?v=1OmJJwVF7uQ
https://velog.io/@wansook0316/Task-TaskGroup
https://eunjin3786.tistory.com/459

2022-11-18 13:25 UTC, PecanPiePOS reviewed
아직 User 의 Artist 로 정보를 보내는 것과 UI 수정 부분은 남았지만 우선 기능적인 것이 우선순위가 높다고 판단하여 빠르게 PR 올립니다.

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Global/Utils/FirebaseManager.swift
> +    }
원래는 [UIImage] 를 받아 해당 URL [String] 으로 리턴하려 했으나, concurrent 로 작업을 하려고 하나의 사진과 하나의 String 으로 기능을 만들었습니다.

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Global/Utils/FirebaseManager.swift
> +    }
더불어 Storage 에 저장될 파일들이 겹치지 않기 위해 fileName 에 hashValue 를 붙여 만들었는데, 
혹시 다른 의견 있으신 분들은 말씀해주세요!

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Models/Artist.swift
> +}
이것도 논의를 해야할 것 같은데 한 줄 소개는 빼고 하는 것은 어떨까요?
일부러 한줄 소개는 넣지 않았습니다.
-- 귀찮아서 뷰 안그린거 아닙니다^^

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +    private var dataSourceToServer = Artist(city: [], camera: "", lens: "", detailDescription: "", portfolioImageUrls: [])
각 유저의 인스턴스를 만들어 저장하기 위해 따로 뺏습니다.
User 에서 현재 Artist 정보가 속해있지 않기 때문에, 이렇게 만들어만 놨습니다.

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +    }
로딩뷰 입니다. 시간이 급해서 따로 LoadingView 로 빼지않고 작업했습니다.

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +            }
Task 를 나열하고 비동기로 보낼 작업을 `async let` 으로 받고, 완료를 받게끔 결과값을 `await` 으로 받았습니다.
Task 를 나열함으로써 비동기이면서 동시성을 가진 작업을 만들었습니다.

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +    }
UIActivityIndicatorView 는 default 값이 false 로, startAnimating() 을 하거나, isAnimating = true 하지 않는 이상,
보이지 않습니다. (= isHidden 안먹힘)

2022-11-18 13:25 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/RegisterPortfolioViewController.swift
>                  }
원활한 서버 트렉픽과 저장 공간을 위해 한번 더 compress 했습니다

2022-11-18 18:32 UTC, coby5502 approved these changes
항상 배워갑니다.

2022-11-18 18:32 UTC, coby5502 commented on Flicker/Global/Utils/FirebaseManager.swift
> +            let imageRef = ref.child("ArtistPortfolio/\(fileName).jpg")
p2
ref.child("ArtistPortfolio/\(유저의 Id_인덱스).jpg"
추천합니다!

2022-11-18 18:32 UTC, coby5502 commented on Flicker/Models/Artist.swift
> +}
빼고, 메인뷰에서도 없앱시다!

2022-11-19 01:02 UTC, Rookie0031 requested changes
## 고생하셨습니다!

비동기와 동시성에 대해 많은 고민을 하셧군요 짱입니다..👍
궁금한점은 이미지 업로드가 Concurrent하게 진행되면 파이어베이스에 업로드되는 이미지 순서는 어떻게 될까요?? 

이것이 중요한게 작가등록할 때 처음 이미지 4개가 디테일뷰 상단의 대표 포트폴리오 이미지로 들어가게 됩니다.  그래서 만약 작가가 사진 등록한 순서대로 파베에 올라가지 않으면 원하는 사진들이 대표 이미지가 될 수 없을 수도 있기 때문에 확인해주시면 감사하겟음다!!

2022-11-19 01:47 UTC, Rookie0031 approved these changes

2022-11-19 04:13 UTC, PecanPiePOS commented on Flicker/Global/Utils/FirebaseManager.swift
> +            let imageRef = ref.child("ArtistPortfolio/\(fileName).jpg")
의견 감사합니다. 
그렇게 바꾸고 싶은데 혹시 유저 id 는 currentUser.uid 로 받으면 될거같은데, index 는 어떻게 추가해야할까요?

2022-11-19 04:23 UTC, PecanPiePOS commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +                    await self.temporaryStrings.append(urlString)
데이터 구조 상 Artist 내에 저장되는 photos 들은 UIImage 가 아닙니다. Storage 에는 이미지를 저장하고, Database 에는 String 과 같은 Codable 한 데이터만 저장할 수 있기 때문에 각 이미지의 downloadUrl 을 String 으로 받아서 저장합니다.
그래야 나중에 image 를 불러올 때, url: String 으로 받아올 수 있습니다. 다른 다운로드 하는 function 을 봐도 다 string 으로 받아오는데 그러려면 url 로 받아와햐 합니다!

2022-11-19 04:29 UTC, PecanPiePOS commented
@Rookie0031 
루키가 말한 Concurrency 때문에 생기는 랜덤한 다운로드에 대해서는 문제가 없을 것 같습니다. 어차피 Storage 에는 어떻게 파일들이 있든 상관 없기 때문입니다. 다만 받아올 때 신경을 써야할 문제 같습니다. 사진을 전달해주는 phpicker 와 url: [String] 으로 받아오기 때문에 url 네이밍에서 문제를 해결해야할 것 같습니다.

좋은 의견 감사합니다! 꼭 필요한 고민이었습니다!
이거에 대한 우선순위는 살짝 낮추고 버그를 먼저 고치려고 하는데 괜찮을까요? 
-> 일요일에 넣거나 아니면 출시된 이후에 넣어도 괜찮을 것이라 생각이 듭니다! (물론 중요한 문제는 맞습니다)

2022-11-19 07:57 UTC, Kim-Yeon-ho approved these changes
LGTM

2022-11-19 07:57 UTC, Kim-Yeon-ho commented on Flicker/Screens/ArtistRegister/ViewControllers/ArtistRegisterViewController.swift
> +                    await self.temporaryStrings.append(urlString)
p5
Task하나가 스레드 하나로 된다는 것을 알려주셔서 감사합니다.
많이 배웁니다. LGTM

2022-11-19 07:58 UTC, merged